[env:waveshare_lcd_4_3]
platform = espressif32
board = esp32-s3-devkitc-1
#framework = arduino
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
framework = espidf
upload_speed=921600
monitor_speed=115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0
lib_ldf_mode = deep
board_build.psram_type = opi
build_flags = -std=gnu++17
    -DCORE_DEBUG_LEVEL=2
    -DWAVESHARE_LCD_4_3INCH
    -DLV_CONF_INCLUDE_SIMPLE
    -Iinclude
    -mfix-esp32-psram-cache-issue
#upload_port = COM10
#monitor_port = COM10